=== api-evangelist/flipdish/json-schema/apps-app-store-app-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/flipdish/refs/heads/main/json-schema/apps-app-store-app-schema.json",
  "title": "AppStoreApp",
  "description": "AppStoreApp schema from Flipdish API - Apps.",
  "type": "object",
  "properties": {
    "Id": {
      "type": "string",
      "example": "500123"
    },
    "VerificationStatus": {
      "enum": [
        "Draft",
        "Submitted",
        "Verified"
      ],
      "type": "string",
      "example": "Draft"
    },
    "Logo": {
      "type": "string",
      "example": "string"
    },
    "OAuthAppId": {
      "type": "string",
      "example": "500123"
    },
    "Internal": {
      "type": "boolean",
      "example": true
    },
    "Details": {
      "type": "string",
      "example": "string"
    },
    "ConfigurationType": {
      "enum": [
        "ExternalLink",
        "FlipdishHosted"
      ],
      "type": "string",
      "example": "ExternalLink"
    },
    "StoreSelectorType": {
      "enum": [
        "None",
        "Single",
        "Multiple"
      ],
      "type": "string",
      "example": "None"
    },
    "FieldGroups": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/FieldGroup"
      },
      "example": []
    },
    "SetupInstructions": {
      "type": "string",
      "example": "string"
    },
    "ExternalSetupLink": {
      "type": "string",
      "example": "https://api.flipdish.co/example"
    },
    "TeammateAppAccessLevel": {
      "enum": [
        "Owner",
        "StoreOwner",
        "PropertyOwner",
        "ManagedOwner",
        "Integrator",
        "PropertyManager",
        "StoreManager",
        "StoreStaff",
        "StoreReadOnlyAccess",
        "FinanceManger"
      ],
      "type": "string",
      "example": "Owner"
    },
    "PermissionsType": {
      "enum": [
        "Teammate"
      ],
      "type": "string",
      "example": "Teammate"
    },
    "Support": {
      "$ref": "#/components/schemas/AppStoreAppSupportInfo"
    },
    "ExternalFunctionActionUrl": {
      "type": "string",
      "example": "https://api.flipdish.co/example"
    },
    "ExternalFunctionSignatureKey": {
      "type": "string",
      "example": "string"
    },
    "IsPaid": {
      "type": "boolean",
      "example": true
    },
    "Name": {
      "type": "string",
      "example": "Example Name"
    },
    "Description": {
      "type": "string",
      "example": "string"
    },
    "IsEnabled": {
      "type": "boolean",
      "example": true
    },
    "Categories": {
      "type": "array",
      "items": {
        "enum": [
          "PointOfSale",
          "DeliveryAndLogistics",
          "CRM",
          "GiftCard",
          "Accounting",
          "LoyaltyAndMarketing",
          "Other"
        ],
        "type": "string"
      },
      "example": [
        "PointOfSale"
      ]
    },
    "Countries": {
      "type": "array",
      "items": {
        "enum": [
          "GB",
          "IE",
          "FR",
          "ES",
          "PT",
          "IT",
          "DE",
          "PL",
          "BE",
          "LU",
          "NL",
          "US",
          "CA",
          "BG",
          "MX",
          "AU",
          "NZ"
        ],
        "type": "string"
      },
      "example": [
        "GB"
      ]
    },
    "DeveloperName": {
      "type": "string",
      "example": "Example Name"
    }
  },
  "required": [
    "Id",
    "VerificationStatus",
    "OAuthAppId",
    "Internal",
    "Details",
    "ConfigurationType",
    "StoreSelectorType",
    "PermissionsType",
    "Name",
    "Description",
    "Categories",
    "Countries"
  ]
}

=== api-evangelist/flipdish/examples/apps-app-store-app-example.json
{
  "Id": "500123",
  "VerificationStatus": "Draft",
  "Logo": "string",
  "OAuthAppId": "500123",
  "Internal": true,
  "Details": "string",
  "ConfigurationType": "ExternalLink",
  "StoreSelectorType": "None",
  "FieldGroups": [],
  "SetupInstructions": "string",
  "ExternalSetupLink": "https://api.flipdish.co/example",
  "TeammateAppAccessLevel": "Owner",
  "PermissionsType": "Teammate",
  "Support": "string",
  "ExternalFunctionActionUrl": "https://api.flipdish.co/example",
  "ExternalFunctionSignatureKey": "string",
  "IsPaid": true,
  "Name": "Example Name",
  "Description": "string",
  "IsEnabled": true,
  "Categories": [
    "PointOfSale"
  ],
  "Countries": [
    "GB"
  ],
  "DeveloperName": "Example Name"
}
