=== api-evangelist/flipdish/json-schema/catalog-group-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/flipdish/refs/heads/main/json-schema/catalog-group-schema.json",
  "title": "Group",
  "description": "CatalogGroup",
  "type": "object",
  "properties": {
    "CatalogGroupId": {
      "description": "Unique catalog group id",
      "maxLength": 30,
      "minLength": 0,
      "type": "string",
      "example": "500123"
    },
    "CatalogItemId": {
      "description": "Unique catalog item id",
      "maxLength": 30,
      "minLength": 0,
      "type": "string",
      "example": "500123"
    },
    "IsArchived": {
      "description": "Returns true if the group is archived",
      "type": "boolean",
      "example": true
    },
    "MinSelectCount": {
      "format": "int32",
      "description": "Minimum number of items that the user has to select",
      "type": "integer",
      "example": 3
    },
    "MaxSelectCount": {
      "format": "int32",
      "description": "Maximum number of items that the user has to select",
      "type": "integer",
      "nullable": true,
      "example": 3
    },
    "Products": {
      "description": "Collection of items associated with this product",
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/ProductReference"
      },
      "example": []
    },
    "Metafields": {
      "description": "Collection of metafields",
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Metafield"
      },
      "example": []
    },
    "GroupType": {
      "description": "Type of group (ModifierGroup, etc)",
      "enum": [
        "ModifierGroup"
      ],
      "type": "string",
      "example": "ModifierGroup"
    },
    "Sku": {
      "description": "Stock Keeping Unit (SKU)",
      "maxLength": 30,
      "minLength": 0,
      "type": "string",
      "example": "string"
    },
    "Name": {
      "description": "Group name",
      "maxLength": 300,
      "minLength": 0,
      "type": "string",
      "example": "Example Name"
    },
    "AutogenerateDisplayText": {
      "description": "Autogenerate display text in ordering applications",
      "type": "boolean",
      "example": true
    },
    "ImageFileName": {
      "description": "Image File Name",
      "maxLength": 512,
      "minLength": 0,
      "type": "string",
      "example": "Example Name"
    }
  },
  "required": [
    "GroupType",
    "Sku",
    "Name"
  ]
}

=== api-evangelist/flipdish/examples/catalog-group-example.json
{
  "CatalogGroupId": "500123",
  "CatalogItemId": "500123",
  "IsArchived": true,
  "MinSelectCount": 3,
  "MaxSelectCount": 3,
  "Products": [],
  "Metafields": [],
  "GroupType": "ModifierGroup",
  "Sku": "string",
  "Name": "Example Name",
  "AutogenerateDisplayText": true,
  "ImageFileName": "Example Name"
}
