=== api-evangelist/flipdish/json-schema/customers-store-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/flipdish/refs/heads/main/json-schema/customers-store-summary-schema.json",
  "title": "StoreSummary",
  "description": "Store summary",
  "type": "object",
  "properties": {
    "Id": {
      "format": "int32",
      "description": "Store identifier",
      "type": "integer",
      "example": 500123
    },
    "Name": {
      "description": "Store name",
      "type": "string",
      "example": "Example Name"
    },
    "MenuId": {
      "format": "int32",
      "description": "Stores menu identifier",
      "type": "integer",
      "example": 500123
    },
    "MenuPublishId": {
      "format": "uuid",
      "description": "Stores menu publish GUID",
      "type": "string",
      "example": "00000000-0000-0000-0000-000000000000"
    },
    "Metadata": {
      "description": "Store metadata",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "Currency": {
      "description": "Currency which used by the Store",
      "enum": [
        "EUR",
        "USD",
        "GBP",
        "CAD",
        "AUD",
        "DJF",
        "ZAR",
        "ETB",
        "AED",
        "BHD",
        "DZD",
        "EGP",
        "IQD",
        "JOD",
        "KWD",
        "LBP",
        "LYD",
        "MAD",
        "OMR",
        "QAR",
        "SAR",
        "SYP",
        "TND",
        "YER",
        "CLP",
        "INR",
        "AZN",
        "RUB",
        "BYN",
        "BGN",
        "NGN",
        "BDT",
        "CNY",
        "BAM",
        "CZK",
        "DKK",
        "CHF",
        "MVR",
        "BTN",
        "XCD",
        "BZD",
        "HKD",
        "IDR",
        "JMD",
        "MYR",
        "NZD",
        "PHP",
        "SGD",
        "TTD",
        "XDR",
        "ARS",
        "BOB",
        "COP",
        "CRC",
        "CUP",
        "DOP",
        "GTQ",
        "HNL",
        "MXN",
        "NIO",
        "PAB",
        "PEN",
        "PYG",
        "UYU",
        "VEF",
        "IRR",
        "XOF",
        "CDF",
        "XAF",
        "HTG",
        "ILS",
        "HRK",
        "HUF",
        "AMD",
        "ISK",
        "JPY",
        "GEL",
        "KZT",
        "KHR",
        "KRW",
        "KGS",
        "LAK",
        "MKD",
        "MNT",
        "BND",
        "MMK",
        "NOK",
        "NPR",
        "PKR",
        "PLN",
        "AFN",
        "BRL",
        "MDL",
        "RON",
        "RWF",
        "SEK",
        "LKR",
        "SOS",
        "ALL",
        "RSD",
        "KES",
        "TJS",
        "THB",
        "ERN",
        "TMT",
        "BWP",
        "TRY",
        "UAH",
        "UZS",
        "VND",
        "MOP",
        "TWD",
        "BMD"
      ],
      "type": "string",
      "example": "EUR"
    },
    "Coordinates": {
      "$ref": "#/components/schemas/Coordinates"
    },
    "StoreTimezone": {
      "description": "Timezone of store",
      "type": "string",
      "example": "string"
    },
    "StoreIanaTimezone": {
      "description": "IANA Timezone of store",
      "type": "string",
      "example": "string"
    },
    "StoreGroupId": {
      "format": "int32",
      "description": "Store group id of store",
      "type": "integer",
      "example": 500123
    },
    "TaxId": {
      "description": "VAT number or generic Tax ID of the store",
      "type": "string",
      "example": "500123"
    },
    "PrettyAddress": {
      "description": "Address of the store",
      "type": "string",
      "example": "string"
    },
    "CountryCode": {
      "description": "Country code of the store address (ISO 3166-1 alpha-2)",
      "type": "string",
      "example": "IE"
    },
    "PropertyId": {
      "description": "Property identifier",
      "type": "string",
      "example": "500123"
    }
  }
}

=== api-evangelist/flipdish/examples/customers-store-summary-example.json
{
  "Id": 500123,
  "Name": "Example Name",
  "MenuId": 500123,
  "MenuPublishId": "00000000-0000-0000-0000-000000000000",
  "Metadata": {},
  "Currency": "EUR",
  "Coordinates": "string",
  "StoreTimezone": "string",
  "StoreIanaTimezone": "string",
  "StoreGroupId": 500123,
  "TaxId": "500123",
  "PrettyAddress": "string",
  "CountryCode": "IE",
  "PropertyId": "500123"
}
