=== api-evangelist/flipdish/json-schema/payments-payout-refund-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/flipdish/refs/heads/main/json-schema/payments-payout-refund-schema.json",
  "title": "PayoutRefund",
  "description": "Holds the information for a refund related to a payout",
  "type": "object",
  "properties": {
    "OrderId": {
      "format": "int32",
      "description": "The id of the order the refund was for",
      "type": "integer",
      "example": 500123
    },
    "OrderCurrency": {
      "description": "Order currency",
      "enum": [
        "EUR",
        "USD",
        "GBP",
        "CAD",
        "AUD",
        "DJF",
        "ZAR",
        "ETB",
        "AED",
        "BHD",
        "DZD",
        "EGP",
        "IQD",
        "JOD",
        "KWD",
        "LBP",
        "LYD",
        "MAD",
        "OMR",
        "QAR",
        "SAR",
        "SYP",
        "TND",
        "YER",
        "CLP",
        "INR",
        "AZN",
        "RUB",
        "BYN",
        "BGN",
        "NGN",
        "BDT",
        "CNY",
        "BAM",
        "CZK",
        "DKK",
        "CHF",
        "MVR",
        "BTN",
        "XCD",
        "BZD",
        "HKD",
        "IDR",
        "JMD",
        "MYR",
        "NZD",
        "PHP",
        "SGD",
        "TTD",
        "XDR",
        "ARS",
        "BOB",
        "COP",
        "CRC",
        "CUP",
        "DOP",
        "GTQ",
        "HNL",
        "MXN",
        "NIO",
        "PAB",
        "PEN",
        "PYG",
        "UYU",
        "VEF",
        "IRR",
        "XOF",
        "CDF",
        "XAF",
        "HTG",
        "ILS",
        "HRK",
        "HUF",
        "AMD",
        "ISK",
        "JPY",
        "GEL",
        "KZT",
        "KHR",
        "KRW",
        "KGS",
        "LAK",
        "MKD",
        "MNT",
        "BND",
        "MMK",
        "NOK",
        "NPR",
        "PKR",
        "PLN",
        "AFN",
        "BRL",
        "MDL",
        "RON",
        "RWF",
        "SEK",
        "LKR",
        "SOS",
        "ALL",
        "RSD",
        "KES",
        "TJS",
        "THB",
        "ERN",
        "TMT",
        "BWP",
        "TRY",
        "UAH",
        "UZS",
        "VND",
        "MOP",
        "TWD",
        "BMD"
      ],
      "type": "string",
      "example": "EUR"
    },
    "PayoutId": {
      "format": "int32",
      "description": "The id of the payout the order is related to",
      "type": "integer",
      "example": 500123
    },
    "OrderDate": {
      "format": "date-time",
      "description": "The date the order was placed",
      "type": "string",
      "example": "2026-06-02T12:00:00Z"
    },
    "OrderType": {
      "description": "Order type (online or cash)",
      "enum": [
        "Cash",
        "Online"
      ],
      "type": "string",
      "example": "Cash"
    },
    "RefundDate": {
      "format": "date-time",
      "description": "The date the refund was done",
      "type": "string",
      "example": "2026-06-02T12:00:00Z"
    },
    "StoreId": {
      "format": "int32",
      "description": "Store id",
      "type": "integer",
      "example": 500123
    },
    "TotalRefund": {
      "format": "double",
      "description": "Total refund amount",
      "type": "number",
      "example": 12.5
    },
    "RefundedFees": {
      "format": "double",
      "description": "Refunded fees amount",
      "type": "number",
      "example": 12.5
    },
    "RefundedAmount": {
      "format": "double",
      "description": "Refunded amount",
      "type": "number",
      "example": 12.5
    },
    "CashFeeRefundedToCustomer": {
      "format": "double",
      "description": "Cash fee refunded to customer",
      "type": "number",
      "example": 12.5
    }
  }
}

=== api-evangelist/flipdish/examples/payments-payout-refund-example.json
{
  "OrderId": 500123,
  "OrderCurrency": "EUR",
  "PayoutId": 500123,
  "OrderDate": "2026-06-02T12:00:00Z",
  "OrderType": "Cash",
  "RefundDate": "2026-06-02T12:00:00Z",
  "StoreId": 500123,
  "TotalRefund": 12.5,
  "RefundedFees": 12.5,
  "RefundedAmount": 12.5,
  "CashFeeRefundedToCustomer": 12.5
}
