=== api-evangelist/flipdish/json-schema/platform-customer-delivery-tracking-order-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/flipdish/refs/heads/main/json-schema/platform-customer-delivery-tracking-order-schema.json",
  "title": "CustomerDeliveryTrackingOrder",
  "description": "Defines the order data required for customer driver tracking",
  "type": "object",
  "properties": {
    "OrderId": {
      "format": "int32",
      "description": "Order Id",
      "type": "integer",
      "example": 500123
    },
    "Address": {
      "description": "Pretified address string in country format",
      "type": "string",
      "example": "string"
    },
    "DeliveryNotes": {
      "description": "Delivery Notes",
      "type": "string",
      "example": "string"
    },
    "StorePhoneNumber": {
      "description": "Phone number of the store",
      "type": "string",
      "example": "+353000000000"
    },
    "AppIconUrl": {
      "description": "App Icon of the store",
      "type": "string",
      "example": "https://api.flipdish.co/example"
    },
    "OrderTrackingCode": {
      "description": "Order Tracking Code",
      "type": "string",
      "example": "string"
    },
    "PaymentMethodDescription": {
      "description": "Payment method description i.e Cash/Card/iDeal/Paypal",
      "type": "string",
      "example": "string"
    },
    "LastFourDigits": {
      "description": "Last 4 digits of the card if applicable otherwise null",
      "type": "string",
      "example": "string"
    },
    "OrderLines": {
      "description": "Order lines of the order",
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/CustomerDeliveryTrackingOrderLine"
      },
      "example": []
    },
    "TotalAmount": {
      "format": "double",
      "description": "Total amount for the order including tax",
      "type": "number",
      "example": 12.5
    },
    "Currency": {
      "description": "Currency",
      "enum": [
        "EUR",
        "USD",
        "GBP",
        "CAD",
        "AUD",
        "DJF",
        "ZAR",
        "ETB",
        "AED",
        "BHD",
        "DZD",
        "EGP",
        "IQD",
        "JOD",
        "KWD",
        "LBP",
        "LYD",
        "MAD",
        "OMR",
        "QAR",
        "SAR",
        "SYP",
        "TND",
        "YER",
        "CLP",
        "INR",
        "AZN",
        "RUB",
        "BYN",
        "BGN",
        "NGN",
        "BDT",
        "CNY",
        "BAM",
        "CZK",
        "DKK",
        "CHF",
        "MVR",
        "BTN",
        "XCD",
        "BZD",
        "HKD",
        "IDR",
        "JMD",
        "MYR",
        "NZD",
        "PHP",
        "SGD",
        "TTD",
        "XDR",
        "ARS",
        "BOB",
        "COP",
        "CRC",
        "CUP",
        "DOP",
        "GTQ",
        "HNL",
        "MXN",
        "NIO",
        "PAB",
        "PEN",
        "PYG",
        "UYU",
        "VEF",
        "IRR",
        "XOF",
        "CDF",
        "XAF",
        "HTG",
        "ILS",
        "HRK",
        "HUF",
        "AMD",
        "ISK",
        "JPY",
        "GEL",
        "KZT",
        "KHR",
        "KRW",
        "KGS",
        "LAK",
        "MKD",
        "MNT",
        "BND",
        "MMK",
        "NOK",
        "NPR",
        "PKR",
        "PLN",
        "AFN",
        "BRL",
        "MDL",
        "RON",
        "RWF",
        "SEK",
        "LKR",
        "SOS",
        "ALL",
        "RSD",
        "KES",
        "TJS",
        "THB",
        "ERN",
        "TMT",
        "BWP",
        "TRY",
        "UAH",
        "UZS",
        "VND",
        "MOP",
        "TWD",
        "BMD"
      ],
      "type": "string",
      "example": "EUR"
    },
    "Latitude": {
      "format": "double",
      "description": "Customer Location Latitude",
      "type": "number",
      "example": 1.0
    },
    "Longitude": {
      "format": "double",
      "description": "Customer Location Longitude",
      "type": "number",
      "example": 1.0
    },
    "Placed": {
      "format": "date-time",
      "description": "Order placed time",
      "type": "string",
      "example": "2026-06-02T12:00:00Z"
    },
    "RequestedFor": {
      "format": "date-time",
      "description": "Order requested for",
      "type": "string",
      "example": "2026-06-02T12:00:00Z"
    },
    "DriverId": {
      "format": "int32",
      "description": "Driver Id",
      "type": "integer",
      "nullable": true,
      "example": 500123
    },
    "DriverName": {
      "description": "Driver Name",
      "type": "string",
      "example": "Example Name"
    },
    "DriverImage": {
      "description": "Driver Image",
      "type": "string",
      "example": "string"
    },
    "EstimatedMinutesForDelivery": {
      "format": "int32",
      "description": "",
      "type": "integer",
      "example": 1
    }
  }
}

=== api-evangelist/flipdish/examples/platform-customer-delivery-tracking-order-example.json
{
  "OrderId": 500123,
  "Address": "string",
  "DeliveryNotes": "string",
  "StorePhoneNumber": "+353000000000",
  "AppIconUrl": "https://api.flipdish.co/example",
  "OrderTrackingCode": "string",
  "PaymentMethodDescription": "string",
  "LastFourDigits": "string",
  "OrderLines": [],
  "TotalAmount": 12.5,
  "Currency": "EUR",
  "Latitude": 1.0,
  "Longitude": 1.0,
  "Placed": "2026-06-02T12:00:00Z",
  "RequestedFor": "2026-06-02T12:00:00Z",
  "DriverId": 500123,
  "DriverName": "Example Name",
  "DriverImage": "string",
  "EstimatedMinutesForDelivery": 1
}
