=== api-evangelist/flipdish/json-schema/stores-store-end-of-day-report-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/flipdish/refs/heads/main/json-schema/stores-store-end-of-day-report-schema.json",
  "title": "StoreEndOfDayReport",
  "description": "Store end of day report",
  "type": "object",
  "properties": {
    "StoreId": {
      "format": "int32",
      "description": "Store Id",
      "type": "integer",
      "example": 500123
    },
    "StoreName": {
      "description": "Store name",
      "type": "string",
      "example": "Example Name"
    },
    "Currency": {
      "description": "Currency",
      "enum": [
        "EUR",
        "USD",
        "GBP",
        "CAD",
        "AUD",
        "DJF",
        "ZAR",
        "ETB",
        "AED",
        "BHD",
        "DZD",
        "EGP",
        "IQD",
        "JOD",
        "KWD",
        "LBP",
        "LYD",
        "MAD",
        "OMR",
        "QAR",
        "SAR",
        "SYP",
        "TND",
        "YER",
        "CLP",
        "INR",
        "AZN",
        "RUB",
        "BYN",
        "BGN",
        "NGN",
        "BDT",
        "CNY",
        "BAM",
        "CZK",
        "DKK",
        "CHF",
        "MVR",
        "BTN",
        "XCD",
        "BZD",
        "HKD",
        "IDR",
        "JMD",
        "MYR",
        "NZD",
        "PHP",
        "SGD",
        "TTD",
        "XDR",
        "ARS",
        "BOB",
        "COP",
        "CRC",
        "CUP",
        "DOP",
        "GTQ",
        "HNL",
        "MXN",
        "NIO",
        "PAB",
        "PEN",
        "PYG",
        "UYU",
        "VEF",
        "IRR",
        "XOF",
        "CDF",
        "XAF",
        "HTG",
        "ILS",
        "HRK",
        "HUF",
        "AMD",
        "ISK",
        "JPY",
        "GEL",
        "KZT",
        "KHR",
        "KRW",
        "KGS",
        "LAK",
        "MKD",
        "MNT",
        "BND",
        "MMK",
        "NOK",
        "NPR",
        "PKR",
        "PLN",
        "AFN",
        "BRL",
        "MDL",
        "RON",
        "RWF",
        "SEK",
        "LKR",
        "SOS",
        "ALL",
        "RSD",
        "KES",
        "TJS",
        "THB",
        "ERN",
        "TMT",
        "BWP",
        "TRY",
        "UAH",
        "UZS",
        "VND",
        "MOP",
        "TWD",
        "BMD"
      ],
      "type": "string",
      "example": "EUR"
    },
    "OrderCount": {
      "format": "int32",
      "description": "Order Count",
      "type": "integer",
      "example": 3
    },
    "OrderValue": {
      "format": "double",
      "description": "Order Value",
      "type": "number",
      "example": 1.0
    },
    "OrderValueExcludingDeliveryFees": {
      "format": "double",
      "description": "Order Value Excluding Delivery Fees",
      "type": "number",
      "example": 12.5
    },
    "CollectionOrderCount": {
      "format": "int32",
      "description": "Collection Order Count",
      "type": "integer",
      "example": 3
    },
    "CollectionCashOrderCount": {
      "format": "int32",
      "description": "Collection Cash Order Count",
      "type": "integer",
      "example": 3
    },
    "CollectionPaidOnlineOrderCount": {
      "format": "int32",
      "description": "Collection Paid Online Order Count",
      "type": "integer",
      "example": 3
    },
    "CollectionOrderValue": {
      "format": "double",
      "description": "Collection Order Value",
      "type": "number",
      "example": 1.0
    },
    "CollectionCashOrderValue": {
      "format": "double",
      "description": "Collection Cash Order Value",
      "type": "number",
      "example": 1.0
    },
    "CollectionPaidOnlineOrderValue": {
      "format": "double",
      "description": "Collection Paid Online Order Value",
      "type": "number",
      "example": 1.0
    },
    "DeliveryOrderCount": {
      "format": "int32",
      "description": "Delivery Order Count",
      "type": "integer",
      "example": 3
    },
    "DeliveryCashOrderCount": {
      "format": "int32",
      "description": "Delivery Cash Order Count",
      "type": "integer",
      "example": 3
    },
    "DeliveryPaidOnlineOrderCount": {
      "format": "int32",
      "description": "Delivery Paid Online Order Count",
      "type": "integer",
      "example": 3
    },
    "DeliveryOrderValue": {
      "format": "double",
      "description": "Delivery Order Value",
      "type": "number",
      "example": 1.0
    },
    "DeliveryCashOrderValue": {
      "format": "double",
      "description": "Delivery Cash Order Value",
      "type": "number",
      "example": 1.0
    },
    "DeliveryPaidOnlineOrderValue": {
      "format": "double",
      "description": "Delivery Paid Online Order Value",
      "type": "number",
      "example": 1.0
    },
    "PaidOnlineOrderCount": {
      "format": "int32",
      "description": "Paid Online Order Count",
      "type": "integer",
      "example": 3
    },
    "CashOrderCount": {
      "format": "int32",
      "description": "Cash Order Count",
      "type": "integer",
      "example": 3
    },
    "PaidOnlineOrderValue": {
      "format": "double",
      "description": "Paid Online Order Value",
      "type": "number",
      "example": 1.0
    },
    "CashOrderValue": {
      "format": "double",
      "description": "Cash Order Value",
      "type": "number",
      "example": 1.0
    },
    "PaidOnlineOrderValueExcludingDeliveryFees": {
      "format": "double",
      "description": "Paid Online Order Value Excluding Delivery Fees",
      "type": "number",
      "example": 12.5
    },
    "CashOrderValueExcludingDeliveryFees": {
      "format": "double",
      "description": "Cash Order Value Excluding Delivery Fees",
      "type": "number",
      "example": 12.5
    },
    "StartTime": {
      "format": "date-time",
      "description": "Start Time",
      "type": "string",
      "example": "2026-06-02T12:00:00Z"
    },
    "EndTime": {
      "format": "date-time",
      "description": "End Time",
      "type": "string",
      "example": "2026-06-02T12:00:00Z"
    }
  }
}

=== api-evangelist/flipdish/examples/stores-store-end-of-day-report-example.json
{
  "StoreId": 500123,
  "StoreName": "Example Name",
  "Currency": "EUR",
  "OrderCount": 3,
  "OrderValue": 1.0,
  "OrderValueExcludingDeliveryFees": 12.5,
  "CollectionOrderCount": 3,
  "CollectionCashOrderCount": 3,
  "CollectionPaidOnlineOrderCount": 3,
  "CollectionOrderValue": 1.0,
  "CollectionCashOrderValue": 1.0,
  "CollectionPaidOnlineOrderValue": 1.0,
  "DeliveryOrderCount": 3,
  "DeliveryCashOrderCount": 3,
  "DeliveryPaidOnlineOrderCount": 3,
  "DeliveryOrderValue": 1.0,
  "DeliveryCashOrderValue": 1.0,
  "DeliveryPaidOnlineOrderValue": 1.0,
  "PaidOnlineOrderCount": 3,
  "CashOrderCount": 3,
  "PaidOnlineOrderValue": 1.0,
  "CashOrderValue": 1.0,
  "PaidOnlineOrderValueExcludingDeliveryFees": 12.5,
  "CashOrderValueExcludingDeliveryFees": 12.5,
  "StartTime": "2026-06-02T12:00:00Z",
  "EndTime": "2026-06-02T12:00:00Z"
}
